#!/usr/bin/env python3
"""Non-destructive FTP inventory and legacy SQLite schema audit for Matnyaab."""

from __future__ import annotations

import ftplib
import os
import posixpath
import sqlite3
import sys
import tempfile
from pathlib import Path
from urllib.parse import urlparse

SERVER = os.environ["FTP_SERVER"].strip()
USER = os.environ["FTP_USER"]
PASSWORD = os.environ["FTP_PASSWORD"]

MAX_ENTRIES = 10000
DB_CANDIDATES = [
    "matnyaab_with_license/db.sqlite3",
    "db.sqlite3",
]


def parse_endpoint(value: str):
    raw = value if "://" in value else f"ftp://{value}"
    parsed = urlparse(raw)
    if not parsed.hostname:
        raise SystemExit("Could not parse FTP_SERVER")
    return parsed.scheme.lower(), parsed.hostname, parsed.port or (990 if parsed.scheme == "ftps" else 21), parsed.path.strip("/")


def connect():
    scheme, host, port, base_path = parse_endpoint(SERVER)
    if scheme == "ftps":
        ftp = ftplib.FTP_TLS()
    else:
        ftp = ftplib.FTP()
    ftp.connect(host, port, timeout=30)
    ftp.login(USER, PASSWORD)
    if isinstance(ftp, ftplib.FTP_TLS):
        ftp.prot_p()
    if base_path:
        ftp.cwd(base_path)
    return ftp


def walk_mlsd(ftp: ftplib.FTP):
    rows = []
    stack = [""]
    while stack:
        rel = stack.pop()
        try:
            entries = list(ftp.mlsd(rel or "."))
        except Exception as exc:
            rows.append((rel or ".", "WARN", f"MLSD failed: {type(exc).__name__}"))
            continue
        for name, facts in entries:
            if name in (".", ".."):
                continue
            child = posixpath.join(rel, name) if rel else name
            kind = facts.get("type", "unknown")
            size = facts.get("size", "")
            rows.append((child, kind, size))
            if len(rows) >= MAX_ENTRIES:
                rows.append(("...", "WARN", f"inventory capped at {MAX_ENTRIES} entries"))
                return rows
            if kind == "dir":
                stack.append(child)
    return rows


def remote_exists(ftp: ftplib.FTP, path: str) -> bool:
    parent, name = posixpath.split(path)
    try:
        for entry_name, facts in ftp.mlsd(parent or "."):
            if entry_name == name and facts.get("type") == "file":
                return True
    except Exception:
        try:
            size = ftp.size(path)
            return size is not None
        except Exception:
            return False
    return False


def download(ftp: ftplib.FTP, remote: str, local: Path):
    with local.open("wb") as fh:
        ftp.retrbinary(f"RETR {remote}", fh.write)


def quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def sqlite_report(db_path: Path) -> str:
    con = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    cur = con.cursor()

    integrity = cur.execute("PRAGMA integrity_check").fetchone()[0]
    version = cur.execute("select sqlite_version()").fetchone()[0]
    objects = cur.execute(
        """
        SELECT type, name, tbl_name, sql
        FROM sqlite_master
        WHERE name NOT LIKE 'sqlite_%'
        ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 ELSE 2 END, name
        """
    ).fetchall()

    lines = [
        "# Legacy SQLite audit",
        "",
        f"- SQLite runtime: `{version}`",
        f"- Integrity check: `{integrity}`",
        "",
        "## Table row counts",
        "",
        "| Table | Rows |",
        "|---|---:|",
    ]

    tables = [name for typ, name, _tbl, _sql in objects if typ == "table"]
    for table in tables:
        try:
            count = cur.execute(f"SELECT COUNT(*) FROM {quote_ident(table)}").fetchone()[0]
            lines.append(f"| `{table}` | {count} |")
        except Exception as exc:
            lines.append(f"| `{table}` | ERROR: {type(exc).__name__} |")

    lines += ["", "## Schema", ""]
    for typ, name, tbl, sql in objects:
        if not sql:
            continue
        lines += [
            f"### {typ}: `{name}`",
            "",
            "```sql",
            sql.rstrip(";") + ";",
            "```",
            "",
        ]

    con.close()
    return "\n".join(lines)


def main():
    out_dir = Path("docs/runtime")
    out_dir.mkdir(parents=True, exist_ok=True)

    ftp = connect()
    try:
        rows = walk_mlsd(ftp)
        inventory = [
            "# FTP inventory generated by GitHub Actions",
            "# Format: path<TAB>type<TAB>size-or-note",
        ]
        inventory += [f"{p}\t{k}\t{s}" for p, k, s in sorted(rows)]
        (out_dir / "ftp-inventory.txt").write_text("\n".join(inventory) + "\n", encoding="utf-8")

        found = None
        for candidate in DB_CANDIDATES:
            if remote_exists(ftp, candidate):
                found = candidate
                break

        if not found:
            (out_dir / "legacy-db-schema.md").write_text(
                "# Legacy SQLite audit\n\nNo `db.sqlite3` was found at the expected paths.\n",
                encoding="utf-8",
            )
            print("WARNING: db.sqlite3 not found at expected paths")
            return 0

        with tempfile.TemporaryDirectory() as tmp:
            local = Path(tmp) / "db.sqlite3"
            download(ftp, found, local)
            report = sqlite_report(local)
            header = f"<!-- Remote source: {found}; no row data is included. -->\n\n"
            (out_dir / "legacy-db-schema.md").write_text(header + report + "\n", encoding="utf-8")
            print(f"Audited SQLite database at: {found}")
    finally:
        try:
            ftp.quit()
        except Exception:
            ftp.close()

    print(f"FTP inventory entries: {len(rows)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
